services:
  golanapi:
    container_name: server-cinema-api
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URI=postgres://postgres:senha123@postgres:5432/cinema_database?sslmode=disable
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cinema_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha123
volumes:
  postgres-data:
